Controllers/QuestionsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using stack_overload.Data;
using stack_overload.Models;
using stack_overload.Models.InputModels;
using stack_overload.Models.ViewModels;

namespace stack_overload.Controllers
{
    public class QuestionsController : Controller
    {
        private UserManager<User> UserManager { get; set; }

        private ApplicationDbContext DbContext { get; set; }

        public QuestionsController(UserManager<User> userManager, ApplicationDbContext dbContext)
        {
            UserManager = userManager;
            DbContext = dbContext;
        }

        [HttpGet]
        public async Task<IActionResult> Index(
            [FromQuery] string tag, [FromQuery] string page, [FromQuery] string sortByMostAnswered
        ) {
            List<QuestionSummaryViewModel> questions = null;
            bool isValidPage = int.TryParse(page, out int pageToVisit);
            bool sortByDate = sortByMostAnswered?.ToLower() == "false" || string.IsNullOrEmpty(sortByMostAnswered);

            if (!isValidPage)
            {
                pageToVisit = 1;
            }

            int questionsToSkip = PaginationViewModel.QuestionsPerPage * (pageToVisit - 1);

            if (string.IsNullOrEmpty(tag))
            {
                IOrderedQueryable<Question> query = sortByDate ? DbContext.Questions.OrderByDescending(q => q.CreatedAt) : DbContext.Questions.OrderByDescending(q => q.Answers.Count());
                
                questions = await query
                                    .Skip(questionsToSkip)
                                    .Take(PaginationViewModel.QuestionsPerPage)
                                    .Select(q => new QuestionSummaryViewModel()
                                    {
                                        Id = q.Id,
                                        Title = q.Title,
                                        QuestionCreator = q.CreatedBy.UserName,
                                        AnswersCount = q.Answers.Count(),
                                        Tags = q.Tags.ToList()
                                    })
                                    .ToListAsync();
            }
            else
            {
                IOrderedQueryable<Question> query = sortByDate ? DbContext.Questions.Where(q => q.Tags.Any(t => t.Name == tag)).OrderByDescending(q => q.CreatedAt) : DbContext.Questions.Where(q => q.Tags.Any(t => t.Name == tag)).OrderByDescending(q => q.Answers.Count());

                questions = await query
                                .Skip(questionsToSkip)
                                .Take(PaginationViewModel.QuestionsPerPage)
                                .Select(q => new QuestionSummaryViewModel()
                                {
                                    Id = q.Id,
                                    Title = q.Title,
                                    QuestionCreator = q.CreatedBy.UserName,
                                    AnswersCount = q.Answers.Count(),
                                    Tags = q.Tags.ToList()
                                })
                                .ToListAsync();
            }

            QuestionIndexViewModel viewModel = new QuestionIndexViewModel();

            viewModel.SummaryOfQuestions = questions;
            viewModel.CurrentPage = pageToVisit;
            viewModel.SortedByDate = sortByDate;
            viewModel.TagForSorting = string.IsNullOrEmpty(tag) ? null : tag;

            return View(viewModel);
        }

        [HttpGet, Authorize]
        public IActionResult New()
        {
            return View();
        }

        [HttpPost, Authorize]
        public async Task<IActionResult> New(NewQuestionInputModel inputModel)
        {
            User currentUser = await UserManager.GetUserAsync(User);

            Question question = new Question(inputModel.Title, inputModel.Body, currentUser.Id);

            DbContext.Questions.Add(question);

            foreach (string tagValue in inputModel.Tags.Split(','))
            {
                Tag tag = new Tag(tagValue);

                question.Tags.Add(tag);

                DbContext.Tags.Add(tag);
            }

            DbContext.SaveChanges();

            return Redirect($"/questions/details/{question.Id}");
        }

        [HttpGet]
        public async Task<IActionResult> Details(string id)
        {
            Question question = await DbContext.Questions
                                                    .Include(q => q.Tags)
                                                    .Include(q => q.Answers)
                                                    .ThenInclude(a => a.CreatedBy)
                                                    .ThenInclude(a => a.Comments)
                                                    .Include(q => q.Comments)
                                                    .Include(q => q.CreatedBy)
                                                    .FirstOrDefaultAsync(q => q.Id == id);

            if (question == null)
                return Redirect("/questions/new");

            User currentUser = User.Identity.IsAuthenticated ? await UserManager.GetUserAsync(User) : null;

            QuestionDetailsViewModel viewModel = new QuestionDetailsViewModel()
            {
                Id = question.Id,
                Title = question.Title,
                Body = question.Body,
                CurrentUserId = currentUser?.Id,
                QuestionCreatorId = question.CreatedById,
                QuestionCreatorName = question.CreatedBy.UserName,
                QuestionCreatorReputation = question.CreatedBy.Reputation,
                Tags = question.Tags,
                Answers = question.Answers,
                Comments = question.Comments,
                Votes = question.Votes
            };

            return View(viewModel);
        }

        [HttpPost, Authorize]
        public async Task<IActionResult> Vote(
            [FromRoute] string id, [FromForm] VoteInputModel inputModel
        ) {
            Question question = await DbContext
                                        .Questions
                                        .Include(q => q.CreatedBy)
                                        .Include(q => q.Upvoters)
                                        .Include(q => q.Downvoters)
                                        .FirstOrDefaultAsync(q => q.Id == id);

            if (question == null)
            {
                return Redirect("~/questions/index");
            }

            User currentUser = await UserManager.GetUserAsync(User);

            if (question.CreatedById == currentUser.Id)
            {
                return Redirect($"~/questions/details/{id}");
            }
            else
            {
                if (inputModel.Action == "upvote")
                {
                    if (question.Downvoters.Any(v => v.Id == currentUser.Id))
                    {
                        question.Votes += 1;
                        question.CreatedBy.Reputation += 5;
                        question.Downvoters.Remove(currentUser);
                    }
                    else if (!question.Upvoters.Any(v => v.Id == currentUser.Id))
                    {
                        question.Votes += 1;
                        question.CreatedBy.Reputation += 5;
                        question.Upvoters.Add(currentUser);
                    }
                    else
                    {
                        return Redirect($"~/questions/details/{id}");
                    }
                }
                else if (inputModel.Action == "downvote")
                {
                    

                    if (question.Upvoters.Any(v => v.Id == currentUser.Id))
                    {
                        question.Votes -= 1;
                        question.CreatedBy.Reputation -= 5;
                        question.Upvoters.Remove(currentUser);
                    }
                    else if (!question.Downvoters.Any(v => v.Id == currentUser.Id))
                    {
                        question.Votes -= 1;
                        question.CreatedBy.Reputation -= 5;
                        question.Downvoters.Add(currentUser);
                    }
                    else
                    {
                        return Redirect($"~/questions/details/{id}");
                    }
                }
                else
                {
                    return Redirect($"~/questions/details/{question.Id}");
                }

                question.UpdatedAt = DateTime.Now;

                await DbContext.SaveChangesAsync();

                return Redirect($"~/questions/details/{id}");
            }
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Stack Overload</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/stack_overload.styles.css" asp-append-version="true" />

    <script src="~/lib/tinymce/tinymce.min.js" referrerpolicy="origin"></script>
    <script>
      tinymce.init({
        selector: '.tinymce-text-area'
      });
    </script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Questions" asp-action="Index">Stack Overload</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Questions" asp-action="New">Ask a question</a>
                        </li>
                        
                        @if (User.IsInRole("Administrator"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="administrative" asp-action="questions">Manage Questions</a>
                            </li>
                        }
                    </ul>

                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - stack_overload - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>